// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL9T7Qa-22wkAF7tqm6shyWAJ4opXOrFo',
    appId: '1:700176131607:web:5fdd9c4c47406fb1bd9e52',
    messagingSenderId: '700176131607',
    projectId: 'influenza-fyp',
    authDomain: 'influenza-fyp.firebaseapp.com',
    storageBucket: 'influenza-fyp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7iMcxdzkcGfHy0d06kJ9UNxXwjcV3d5I',
    appId: '1:700176131607:android:598b0a6e6adddd92bd9e52',
    messagingSenderId: '700176131607',
    projectId: 'influenza-fyp',
    storageBucket: 'influenza-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpWlVGFp7JmfWFYK2zmRCvXPxM72wOlCw',
    appId: '1:700176131607:ios:795db7b3f6015c02bd9e52',
    messagingSenderId: '700176131607',
    projectId: 'influenza-fyp',
    storageBucket: 'influenza-fyp.appspot.com',
    iosBundleId: 'com.example.influenza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpWlVGFp7JmfWFYK2zmRCvXPxM72wOlCw',
    appId: '1:700176131607:ios:3907e1dfc84bfe4fbd9e52',
    messagingSenderId: '700176131607',
    projectId: 'influenza-fyp',
    storageBucket: 'influenza-fyp.appspot.com',
    iosBundleId: 'com.example.influenza.RunnerTests',
  );
}
